apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webapp
  namespace: monitoring
  labels:
    release: monitoring   # âœ… THIS MUST MATCH
spec:
  selector:
    matchLabels:
      app: webapp-deployment
  namespaceSelector:
    matchNames:
      - app
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s
