namespaces:
  create: true
  name: "app"

replicaCount: 2

image:
  repository: kyawzawaung1148/springboot-app
  tag: v5
  pullPolicy: Always

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

database:
  user: petclinic-user
  url: jdbc:mysql://petclinic-mysql-service.database.svc.cluster.local:3306/petclinic-database

secrets:
  mysqlSecretName: mysql-pass
  mysqlPasswordKey: password
