apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: {{ .Values.namespaces.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: webapp-deployment
  template:
    metadata:
      labels:
        app: webapp-deployment
    spec:
      containers:
        - name: webapp-deployment
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
          env:
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.mysqlSecretName }}
                  key: {{ .Values.secrets.mysqlPasswordKey }}
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: database-data
                  key: databaseurl
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: database-data
                  key: user
          ports:
            - containerPort: 8080
