# helm/application/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.name }}
  labels:
    name: {{ .Values.namespaces.name }}
    managed-by: "argocd"

