apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.app }}
  labels:
    name: {{ .Values.namespaces.app }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.database }}
  labels:
    name: {{ .Values.namespaces.database }}
