apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: {{ .Values.namespace }}
data:
  user: "{{ .Values.mysql.user }}"
  databaseurl: "jdbc:mysql://petclinic-mysql-service.database.svc.cluster.local:3306/{{ .Values.mysql.database }}"

