namespace: database

mysql:
  image: mysql
  tag: "8.0"

  database: petclinic-database

  user: petclinic-user

  password: test   

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: "local-path"

service:
  port: 3306
