namespace: database

mysql:
  image: mysql
  tag: "8.0"

  database: petclinic-database

  user: petclinic-user

  password: test   

persistence:
  enabled: true
  storageClass: local-path
  accessMode: ReadWriteOnce
  size: 1Gi

service:
  port: 3306
